# Generated by Django 4.2.1 on 2023-06-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('n', 'News'), ('m', 'Music'), ('s', 'Sport')], default='l', max_length=5),
        ),
    ]
