# Generated by Django 4.2.1 on 2023-05-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='main_character',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
