# Generated by Django 4.2.1 on 2023-05-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_movie_main_character'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='author',
            new_name='director',
        ),
    ]
