# Generated by Django 4.2.1 on 2023-05-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_rename_author_movie_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='main_character',
            new_name='main_actor',
        ),
    ]
