# Generated by Django 4.2.1 on 2023-05-30 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_remove_tag_books_book_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='tags',
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('fr', 'French')], default='ru', max_length=2)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='books.genre')),
                ('tags', models.ManyToManyField(related_name='books', to='books.tag')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='books.publisher'),
        ),
    ]
