# Generated by Django 4.2.1 on 2023-05-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_remove_book_genre_remove_book_tags_publisher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='genre',
        ),
    ]
