# Generated by Django 4.2.1 on 2023-05-30 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_remove_publisher_tags_book_genre_book_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
    ]
