# Generated by Django 4.2.1 on 2023-06-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_alter_book_author_alter_book_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='raiting',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
